sudo: required
language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.5 POSTGISVERSION=2
    - CKANVERSION=2.6 POSTGISVERSION=2
    - CKANVERSION=master POSTGISVERSION=2
services:
    - redis-server
    - postgresql
install:
    - bash bin/travis-build.bash
script: sh bin/travis-run.sh
branches:
  only:
    - travis